# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "42971e68eda54221386b3041bee041e3"
name = "realamorfx"
application_url = "https://releasit-nuevo-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "realamorfx.myshopify.com"

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_draft_orders,read_draft_orders,read_orders,write_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://releasit-nuevo-production.up.railway.app/auth/callback" ]

[app_proxy]
url = "https://releasit-nuevo-production.up.railway.app/api/proxy"
subpath = "releasitnuevo"
prefix = "apps"

[pos]
embedded = false
